website: https://marcely.de
version: ${project.version}
name: PlayerCameraEffect
author: Marcely1199
main: de.marcely.pcel.PlayerCameraEffectPlugin
description: Changes the way how the player sees the world

commands:
    pce: 
      description: Manage the plugin with that command
      usage: /pce